### ISSUE TITLE
Initial Release Roadmap

### ISSUE THREAD

**Issue by NathanielJS1541** [NathanielJS1541/LaTeX_Template#1]
This issue should contain everything needed for the initial release, and be the main link to individual issues.

- [ ] #2
- [ ] #3
- [ ] #4
- [x] Main .tex File
- [ ] #5
- [ ] #6
- [ ] #7
- [x] Documentation
  - [x] Main project README.md
    - [x] Installing a `TeX` distribution
    - [x] Installing perl for makeglossaries command
    - [x] Installing `awk` or `gawk` for the vc bundle
    - [x] Editor and Config
    - [x] ~VC Bundle / Git Hooks~
    - [x] Document Structure
  - [x] Preamble README.md
  - [x] Front Matter README.md
  - [x] Sections README.md

**Comment by NathanielJS1541** [comment]
I have decided I will skip the section on git hooks with the VC bundle for now....
